/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : Tiger.g
 *     -                            On : 2016-03-19 18:44:46
 *     -                for the parser : TigerParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "TigerParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pTigerParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pTigerParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pTigerParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pTigerParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */

#undef	    PARSER
#undef	    RECOGNIZER
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO
#undef		DBG

#define	    PARSER				ctx->pParser
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   TigerParserTokenNames[41+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>",
        (pANTLR3_UINT8) "<UP>",
        (pANTLR3_UINT8) "COMMENT",
        (pANTLR3_UINT8) "DIGIT",
        (pANTLR3_UINT8) "ESC_CHAR",
        (pANTLR3_UINT8) "ESC_WS",
        (pANTLR3_UINT8) "ID",
        (pANTLR3_UINT8) "INTEGER",
        (pANTLR3_UINT8) "LETTER",
        (pANTLR3_UINT8) "STRING",
        (pANTLR3_UINT8) "WHITESPACE",
        (pANTLR3_UINT8) "'&'",
        (pANTLR3_UINT8) "'('",
        (pANTLR3_UINT8) "')'",
        (pANTLR3_UINT8) "'*'",
        (pANTLR3_UINT8) "'+'",
        (pANTLR3_UINT8) "','",
        (pANTLR3_UINT8) "'-'",
        (pANTLR3_UINT8) "'/'",
        (pANTLR3_UINT8) "':'",
        (pANTLR3_UINT8) "':='",
        (pANTLR3_UINT8) "';'",
        (pANTLR3_UINT8) "'<'",
        (pANTLR3_UINT8) "'<='",
        (pANTLR3_UINT8) "'<>'",
        (pANTLR3_UINT8) "'='",
        (pANTLR3_UINT8) "'>'",
        (pANTLR3_UINT8) "'>='",
        (pANTLR3_UINT8) "'break'",
        (pANTLR3_UINT8) "'do'",
        (pANTLR3_UINT8) "'else'",
        (pANTLR3_UINT8) "'end'",
        (pANTLR3_UINT8) "'for'",
        (pANTLR3_UINT8) "'function'",
        (pANTLR3_UINT8) "'if'",
        (pANTLR3_UINT8) "'in'",
        (pANTLR3_UINT8) "'let'",
        (pANTLR3_UINT8) "'nil'",
        (pANTLR3_UINT8) "'then'",
        (pANTLR3_UINT8) "'to'",
        (pANTLR3_UINT8) "'var'",
        (pANTLR3_UINT8) "'while'",
        (pANTLR3_UINT8) "'|'"
       };



// Forward declare the locally static matching functions we have generated.
//
static 
 void
	program    (pTigerParser ctx);
static 
 void
	instructions    (pTigerParser ctx);
static 
 void
	params    (pTigerParser ctx);
static 
 void
	param    (pTigerParser ctx);
static 
 void
	declararion    (pTigerParser ctx);
static 
 void
	instruction    (pTigerParser ctx);
static 
 void
	atom    (pTigerParser ctx);
static 
 void
	value    (pTigerParser ctx);
static 
 void
	addition    (pTigerParser ctx);
static 
 void
	multiplication    (pTigerParser ctx);
static 
 void
	or    (pTigerParser ctx);
static 
 void
	and    (pTigerParser ctx);
static 
 void
	comparison    (pTigerParser ctx);
static void	TigerParserFree(pTigerParser ctx);
static void     TigerParserReset (pTigerParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed.
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "Tiger.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new TigerParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pTigerParser
TigerParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return TigerParserNewSSD(instream, NULL);
}

/** \brief Create a new TigerParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pTigerParser
TigerParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pTigerParser ctx;	    /* Context structure we will build and return   */

    ctx	= (pTigerParser) ANTLR3_CALLOC(1, sizeof(TigerParser));

    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in TigerParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our TigerParser interface
     */
    ctx->program	= program;
    ctx->instructions	= instructions;
    ctx->params	= params;
    ctx->param	= param;
    ctx->declararion	= declararion;
    ctx->instruction	= instruction;
    ctx->atom	= atom;
    ctx->value	= value;
    ctx->addition	= addition;
    ctx->multiplication	= multiplication;
    ctx->or	= or;
    ctx->and	= and;
    ctx->comparison	= comparison;
    ctx->free			= TigerParserFree;
    ctx->reset			= TigerParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;

    /* Install the scope pushing methods.
     */

    /* Install the token table
     */
    PSRSTATE->tokenNames   = TigerParserTokenNames;


    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
TigerParserReset (pTigerParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 TigerParserFree(pTigerParser ctx)
 {
    /* Free any scope memory
     */

	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);


    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }

/** Return token names used by this 
parser

 *
 * The returned pointer is used as an index into the token names table (using the token
 * number as the index).
 *
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames()
{
        return TigerParserTokenNames;
}


/* Declare the bitsets
 */
/** Bitset defining follow set for error recovery in rule state: FOLLOW_instructions_in_program232  */
static	ANTLR3_BITWORD FOLLOW_instructions_in_program232_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_instructions_in_program232	= { FOLLOW_instructions_in_program232_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_instruction_in_instructions244  */
static	ANTLR3_BITWORD FOLLOW_instruction_in_instructions244_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_instruction_in_instructions244	= { FOLLOW_instruction_in_instructions244_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_14_in_instructions250  */
static	ANTLR3_BITWORD FOLLOW_14_in_instructions250_bits[]	= { ANTLR3_UINT64_LIT(0x000008D440000B00) };
static  ANTLR3_BITSET_LIST FOLLOW_14_in_instructions250	= { FOLLOW_14_in_instructions250_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_instruction_in_instructions252  */
static	ANTLR3_BITWORD FOLLOW_instruction_in_instructions252_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000808000) };
static  ANTLR3_BITSET_LIST FOLLOW_instruction_in_instructions252	= { FOLLOW_instruction_in_instructions252_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_23_in_instructions255  */
static	ANTLR3_BITWORD FOLLOW_23_in_instructions255_bits[]	= { ANTLR3_UINT64_LIT(0x000008D440000B00) };
static  ANTLR3_BITSET_LIST FOLLOW_23_in_instructions255	= { FOLLOW_23_in_instructions255_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_instruction_in_instructions257  */
static	ANTLR3_BITWORD FOLLOW_instruction_in_instructions257_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000808000) };
static  ANTLR3_BITSET_LIST FOLLOW_instruction_in_instructions257	= { FOLLOW_instruction_in_instructions257_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_instructions261  */
static	ANTLR3_BITWORD FOLLOW_15_in_instructions261_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_instructions261	= { FOLLOW_15_in_instructions261_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_14_in_params273  */
static	ANTLR3_BITWORD FOLLOW_14_in_params273_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008100) };
static  ANTLR3_BITSET_LIST FOLLOW_14_in_params273	= { FOLLOW_14_in_params273_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_param_in_params277  */
static	ANTLR3_BITWORD FOLLOW_param_in_params277_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000048000) };
static  ANTLR3_BITSET_LIST FOLLOW_param_in_params277	= { FOLLOW_param_in_params277_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_18_in_params280  */
static	ANTLR3_BITWORD FOLLOW_18_in_params280_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_18_in_params280	= { FOLLOW_18_in_params280_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_param_in_params282  */
static	ANTLR3_BITWORD FOLLOW_param_in_params282_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000048000) };
static  ANTLR3_BITSET_LIST FOLLOW_param_in_params282	= { FOLLOW_param_in_params282_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_params288  */
static	ANTLR3_BITWORD FOLLOW_15_in_params288_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_params288	= { FOLLOW_15_in_params288_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_param297  */
static	ANTLR3_BITWORD FOLLOW_ID_in_param297_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000200000) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_param297	= { FOLLOW_ID_in_param297_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_21_in_param299  */
static	ANTLR3_BITWORD FOLLOW_21_in_param299_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_21_in_param299	= { FOLLOW_21_in_param299_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_param301  */
static	ANTLR3_BITWORD FOLLOW_ID_in_param301_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_param301	= { FOLLOW_ID_in_param301_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_42_in_declararion314  */
static	ANTLR3_BITWORD FOLLOW_42_in_declararion314_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_42_in_declararion314	= { FOLLOW_42_in_declararion314_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_declararion316  */
static	ANTLR3_BITWORD FOLLOW_ID_in_declararion316_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000600000) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_declararion316	= { FOLLOW_ID_in_declararion316_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_21_in_declararion319  */
static	ANTLR3_BITWORD FOLLOW_21_in_declararion319_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_21_in_declararion319	= { FOLLOW_21_in_declararion319_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_declararion321  */
static	ANTLR3_BITWORD FOLLOW_ID_in_declararion321_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000400000) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_declararion321	= { FOLLOW_ID_in_declararion321_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_22_in_declararion325  */
static	ANTLR3_BITWORD FOLLOW_22_in_declararion325_bits[]	= { ANTLR3_UINT64_LIT(0x0000008000000B00) };
static  ANTLR3_BITSET_LIST FOLLOW_22_in_declararion325	= { FOLLOW_22_in_declararion325_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_value_in_declararion327  */
static	ANTLR3_BITWORD FOLLOW_value_in_declararion327_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_value_in_declararion327	= { FOLLOW_value_in_declararion327_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_35_in_declararion333  */
static	ANTLR3_BITWORD FOLLOW_35_in_declararion333_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_35_in_declararion333	= { FOLLOW_35_in_declararion333_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_declararion335  */
static	ANTLR3_BITWORD FOLLOW_ID_in_declararion335_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004000) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_declararion335	= { FOLLOW_ID_in_declararion335_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_params_in_declararion337  */
static	ANTLR3_BITWORD FOLLOW_params_in_declararion337_bits[]	= { ANTLR3_UINT64_LIT(0x0000000008200000) };
static  ANTLR3_BITSET_LIST FOLLOW_params_in_declararion337	= { FOLLOW_params_in_declararion337_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_21_in_declararion340  */
static	ANTLR3_BITWORD FOLLOW_21_in_declararion340_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_21_in_declararion340	= { FOLLOW_21_in_declararion340_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_declararion342  */
static	ANTLR3_BITWORD FOLLOW_ID_in_declararion342_bits[]	= { ANTLR3_UINT64_LIT(0x0000000008000000) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_declararion342	= { FOLLOW_ID_in_declararion342_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_27_in_declararion346  */
static	ANTLR3_BITWORD FOLLOW_27_in_declararion346_bits[]	= { ANTLR3_UINT64_LIT(0x000008D440004B00) };
static  ANTLR3_BITSET_LIST FOLLOW_27_in_declararion346	= { FOLLOW_27_in_declararion346_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_instructions_in_declararion348  */
static	ANTLR3_BITWORD FOLLOW_instructions_in_declararion348_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_instructions_in_declararion348	= { FOLLOW_instructions_in_declararion348_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_38_in_instruction364  */
static	ANTLR3_BITWORD FOLLOW_38_in_instruction364_bits[]	= { ANTLR3_UINT64_LIT(0x0000040800000000) };
static  ANTLR3_BITSET_LIST FOLLOW_38_in_instruction364	= { FOLLOW_38_in_instruction364_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_declararion_in_instruction366  */
static	ANTLR3_BITWORD FOLLOW_declararion_in_instruction366_bits[]	= { ANTLR3_UINT64_LIT(0x0000042800000000) };
static  ANTLR3_BITSET_LIST FOLLOW_declararion_in_instruction366	= { FOLLOW_declararion_in_instruction366_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_37_in_instruction369  */
static	ANTLR3_BITWORD FOLLOW_37_in_instruction369_bits[]	= { ANTLR3_UINT64_LIT(0x000008D640004B00) };
static  ANTLR3_BITSET_LIST FOLLOW_37_in_instruction369	= { FOLLOW_37_in_instruction369_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_instructions_in_instruction371  */
static	ANTLR3_BITWORD FOLLOW_instructions_in_instruction371_bits[]	= { ANTLR3_UINT64_LIT(0x000008D640004B00) };
static  ANTLR3_BITSET_LIST FOLLOW_instructions_in_instruction371	= { FOLLOW_instructions_in_instruction371_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_33_in_instruction374  */
static	ANTLR3_BITWORD FOLLOW_33_in_instruction374_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_33_in_instruction374	= { FOLLOW_33_in_instruction374_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_instruction381  */
static	ANTLR3_BITWORD FOLLOW_ID_in_instruction381_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000400000) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_instruction381	= { FOLLOW_ID_in_instruction381_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_22_in_instruction383  */
static	ANTLR3_BITWORD FOLLOW_22_in_instruction383_bits[]	= { ANTLR3_UINT64_LIT(0x0000008000000B00) };
static  ANTLR3_BITSET_LIST FOLLOW_22_in_instruction383	= { FOLLOW_22_in_instruction383_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_value_in_instruction385  */
static	ANTLR3_BITWORD FOLLOW_value_in_instruction385_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_value_in_instruction385	= { FOLLOW_value_in_instruction385_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_36_in_instruction392  */
static	ANTLR3_BITWORD FOLLOW_36_in_instruction392_bits[]	= { ANTLR3_UINT64_LIT(0x0000008000000B00) };
static  ANTLR3_BITSET_LIST FOLLOW_36_in_instruction392	= { FOLLOW_36_in_instruction392_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_value_in_instruction394  */
static	ANTLR3_BITWORD FOLLOW_value_in_instruction394_bits[]	= { ANTLR3_UINT64_LIT(0x0000010000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_value_in_instruction394	= { FOLLOW_value_in_instruction394_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_40_in_instruction396  */
static	ANTLR3_BITWORD FOLLOW_40_in_instruction396_bits[]	= { ANTLR3_UINT64_LIT(0x000008D440004B00) };
static  ANTLR3_BITSET_LIST FOLLOW_40_in_instruction396	= { FOLLOW_40_in_instruction396_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_instructions_in_instruction398  */
static	ANTLR3_BITWORD FOLLOW_instructions_in_instruction398_bits[]	= { ANTLR3_UINT64_LIT(0x0000000100000002) };
static  ANTLR3_BITSET_LIST FOLLOW_instructions_in_instruction398	= { FOLLOW_instructions_in_instruction398_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_32_in_instruction410  */
static	ANTLR3_BITWORD FOLLOW_32_in_instruction410_bits[]	= { ANTLR3_UINT64_LIT(0x000008D440004B00) };
static  ANTLR3_BITSET_LIST FOLLOW_32_in_instruction410	= { FOLLOW_32_in_instruction410_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_instructions_in_instruction412  */
static	ANTLR3_BITWORD FOLLOW_instructions_in_instruction412_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_instructions_in_instruction412	= { FOLLOW_instructions_in_instruction412_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_43_in_instruction420  */
static	ANTLR3_BITWORD FOLLOW_43_in_instruction420_bits[]	= { ANTLR3_UINT64_LIT(0x0000008000000B00) };
static  ANTLR3_BITSET_LIST FOLLOW_43_in_instruction420	= { FOLLOW_43_in_instruction420_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_value_in_instruction422  */
static	ANTLR3_BITWORD FOLLOW_value_in_instruction422_bits[]	= { ANTLR3_UINT64_LIT(0x0000000080000000) };
static  ANTLR3_BITSET_LIST FOLLOW_value_in_instruction422	= { FOLLOW_value_in_instruction422_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_31_in_instruction424  */
static	ANTLR3_BITWORD FOLLOW_31_in_instruction424_bits[]	= { ANTLR3_UINT64_LIT(0x000008D440004B00) };
static  ANTLR3_BITSET_LIST FOLLOW_31_in_instruction424	= { FOLLOW_31_in_instruction424_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_instructions_in_instruction426  */
static	ANTLR3_BITWORD FOLLOW_instructions_in_instruction426_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_instructions_in_instruction426	= { FOLLOW_instructions_in_instruction426_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_34_in_instruction432  */
static	ANTLR3_BITWORD FOLLOW_34_in_instruction432_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_34_in_instruction432	= { FOLLOW_34_in_instruction432_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_instruction434  */
static	ANTLR3_BITWORD FOLLOW_ID_in_instruction434_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000400000) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_instruction434	= { FOLLOW_ID_in_instruction434_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_22_in_instruction436  */
static	ANTLR3_BITWORD FOLLOW_22_in_instruction436_bits[]	= { ANTLR3_UINT64_LIT(0x0000008000000B00) };
static  ANTLR3_BITSET_LIST FOLLOW_22_in_instruction436	= { FOLLOW_22_in_instruction436_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_value_in_instruction438  */
static	ANTLR3_BITWORD FOLLOW_value_in_instruction438_bits[]	= { ANTLR3_UINT64_LIT(0x0000020000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_value_in_instruction438	= { FOLLOW_value_in_instruction438_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_41_in_instruction440  */
static	ANTLR3_BITWORD FOLLOW_41_in_instruction440_bits[]	= { ANTLR3_UINT64_LIT(0x0000008000000B00) };
static  ANTLR3_BITSET_LIST FOLLOW_41_in_instruction440	= { FOLLOW_41_in_instruction440_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_value_in_instruction442  */
static	ANTLR3_BITWORD FOLLOW_value_in_instruction442_bits[]	= { ANTLR3_UINT64_LIT(0x0000000080000000) };
static  ANTLR3_BITSET_LIST FOLLOW_value_in_instruction442	= { FOLLOW_value_in_instruction442_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_31_in_instruction444  */
static	ANTLR3_BITWORD FOLLOW_31_in_instruction444_bits[]	= { ANTLR3_UINT64_LIT(0x000008D440004B00) };
static  ANTLR3_BITSET_LIST FOLLOW_31_in_instruction444	= { FOLLOW_31_in_instruction444_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_instructions_in_instruction446  */
static	ANTLR3_BITWORD FOLLOW_instructions_in_instruction446_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_instructions_in_instruction446	= { FOLLOW_instructions_in_instruction446_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_30_in_instruction452  */
static	ANTLR3_BITWORD FOLLOW_30_in_instruction452_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_30_in_instruction452	= { FOLLOW_30_in_instruction452_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_value_in_instruction459  */
static	ANTLR3_BITWORD FOLLOW_value_in_instruction459_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_value_in_instruction459	= { FOLLOW_value_in_instruction459_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_atom474  */
static	ANTLR3_BITWORD FOLLOW_ID_in_atom474_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_atom474	= { FOLLOW_ID_in_atom474_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_atom481  */
static	ANTLR3_BITWORD FOLLOW_ID_in_atom481_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000004000) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_atom481	= { FOLLOW_ID_in_atom481_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_14_in_atom483  */
static	ANTLR3_BITWORD FOLLOW_14_in_atom483_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000008100) };
static  ANTLR3_BITSET_LIST FOLLOW_14_in_atom483	= { FOLLOW_14_in_atom483_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_atom486  */
static	ANTLR3_BITWORD FOLLOW_ID_in_atom486_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000048000) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_atom486	= { FOLLOW_ID_in_atom486_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_18_in_atom489  */
static	ANTLR3_BITWORD FOLLOW_18_in_atom489_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000100) };
static  ANTLR3_BITSET_LIST FOLLOW_18_in_atom489	= { FOLLOW_18_in_atom489_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ID_in_atom491  */
static	ANTLR3_BITWORD FOLLOW_ID_in_atom491_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000048000) };
static  ANTLR3_BITSET_LIST FOLLOW_ID_in_atom491	= { FOLLOW_ID_in_atom491_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_15_in_atom497  */
static	ANTLR3_BITWORD FOLLOW_15_in_atom497_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000800000) };
static  ANTLR3_BITSET_LIST FOLLOW_15_in_atom497	= { FOLLOW_15_in_atom497_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_23_in_atom499  */
static	ANTLR3_BITWORD FOLLOW_23_in_atom499_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_23_in_atom499	= { FOLLOW_23_in_atom499_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_in_atom506  */
static	ANTLR3_BITWORD FOLLOW_STRING_in_atom506_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_in_atom506	= { FOLLOW_STRING_in_atom506_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INTEGER_in_atom512  */
static	ANTLR3_BITWORD FOLLOW_INTEGER_in_atom512_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INTEGER_in_atom512	= { FOLLOW_INTEGER_in_atom512_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_39_in_atom518  */
static	ANTLR3_BITWORD FOLLOW_39_in_atom518_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_39_in_atom518	= { FOLLOW_39_in_atom518_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_or_in_value533  */
static	ANTLR3_BITWORD FOLLOW_or_in_value533_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_or_in_value533	= { FOLLOW_or_in_value533_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multiplication_in_addition546  */
static	ANTLR3_BITWORD FOLLOW_multiplication_in_addition546_bits[]	= { ANTLR3_UINT64_LIT(0x00000000000A0002) };
static  ANTLR3_BITSET_LIST FOLLOW_multiplication_in_addition546	= { FOLLOW_multiplication_in_addition546_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_addition549  */
static	ANTLR3_BITWORD FOLLOW_set_in_addition549_bits[]	= { ANTLR3_UINT64_LIT(0x0000008000000B00) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_addition549	= { FOLLOW_set_in_addition549_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_multiplication_in_addition555  */
static	ANTLR3_BITWORD FOLLOW_multiplication_in_addition555_bits[]	= { ANTLR3_UINT64_LIT(0x00000000000A0002) };
static  ANTLR3_BITSET_LIST FOLLOW_multiplication_in_addition555	= { FOLLOW_multiplication_in_addition555_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_multiplication569  */
static	ANTLR3_BITWORD FOLLOW_atom_in_multiplication569_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000110002) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_multiplication569	= { FOLLOW_atom_in_multiplication569_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_multiplication572  */
static	ANTLR3_BITWORD FOLLOW_set_in_multiplication572_bits[]	= { ANTLR3_UINT64_LIT(0x0000008000000B00) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_multiplication572	= { FOLLOW_set_in_multiplication572_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_atom_in_multiplication578  */
static	ANTLR3_BITWORD FOLLOW_atom_in_multiplication578_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000110002) };
static  ANTLR3_BITSET_LIST FOLLOW_atom_in_multiplication578	= { FOLLOW_atom_in_multiplication578_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_and_in_or593  */
static	ANTLR3_BITWORD FOLLOW_and_in_or593_bits[]	= { ANTLR3_UINT64_LIT(0x0000100000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_and_in_or593	= { FOLLOW_and_in_or593_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_44_in_or596  */
static	ANTLR3_BITWORD FOLLOW_44_in_or596_bits[]	= { ANTLR3_UINT64_LIT(0x0000008000000B00) };
static  ANTLR3_BITSET_LIST FOLLOW_44_in_or596	= { FOLLOW_44_in_or596_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_and_in_or598  */
static	ANTLR3_BITWORD FOLLOW_and_in_or598_bits[]	= { ANTLR3_UINT64_LIT(0x0000100000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_and_in_or598	= { FOLLOW_and_in_or598_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_comparison_in_and612  */
static	ANTLR3_BITWORD FOLLOW_comparison_in_and612_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002002) };
static  ANTLR3_BITSET_LIST FOLLOW_comparison_in_and612	= { FOLLOW_comparison_in_and612_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_13_in_and615  */
static	ANTLR3_BITWORD FOLLOW_13_in_and615_bits[]	= { ANTLR3_UINT64_LIT(0x0000008000000B00) };
static  ANTLR3_BITSET_LIST FOLLOW_13_in_and615	= { FOLLOW_13_in_and615_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_comparison_in_and617  */
static	ANTLR3_BITWORD FOLLOW_comparison_in_and617_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000002002) };
static  ANTLR3_BITSET_LIST FOLLOW_comparison_in_and617	= { FOLLOW_comparison_in_and617_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_addition_in_comparison631  */
static	ANTLR3_BITWORD FOLLOW_addition_in_comparison631_bits[]	= { ANTLR3_UINT64_LIT(0x000000003F000002) };
static  ANTLR3_BITSET_LIST FOLLOW_addition_in_comparison631	= { FOLLOW_addition_in_comparison631_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_comparison634  */
static	ANTLR3_BITWORD FOLLOW_set_in_comparison634_bits[]	= { ANTLR3_UINT64_LIT(0x0000008000000B00) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_comparison634	= { FOLLOW_set_in_comparison634_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_addition_in_comparison648  */
static	ANTLR3_BITWORD FOLLOW_addition_in_comparison648_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_addition_in_comparison648	= { FOLLOW_addition_in_comparison648_bits, 1	};


/* ==============================================
 * Parsing rules
 */
/**
 * $ANTLR start program
 * Tiger.g:30:1: program : instructions ;
 */
static void
program(pTigerParser ctx)
{
    /* Initialize rule variables
     */

    {
        // Tiger.g:30:9: ( instructions )
        // Tiger.g:30:11: instructions
        {
            FOLLOWPUSH(FOLLOW_instructions_in_program232);
            instructions(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleprogramEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleprogramEx; /* Prevent compiler warnings */
    ruleprogramEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end program */

/**
 * $ANTLR start instructions
 * Tiger.g:33:1: instructions : ( instruction | '(' instruction ( ';' instruction )* ')' );
 */
static void
instructions(pTigerParser ctx)
{
    /* Initialize rule variables
     */

    {
        {
            //  Tiger.g:34:3: ( instruction | '(' instruction ( ';' instruction )* ')' )

            ANTLR3_UINT32 alt2;

            alt2=2;

            switch ( LA(1) )
            {
            case ID:
            case INTEGER:
            case STRING:
            case 30:
            case 34:
            case 36:
            case 38:
            case 39:
            case 43:
            	{
            		alt2=1;
            	}
                break;
            case 14:
            	{
            		alt2=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 2;
                EXCEPTION->state        = 0;


                goto ruleinstructionsEx;

            }

            switch (alt2)
            {
        	case 1:
        	    // Tiger.g:34:5: instruction
        	    {
        	        FOLLOWPUSH(FOLLOW_instruction_in_instructions244);
        	        instruction(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionsEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // Tiger.g:35:5: '(' instruction ( ';' instruction )* ')'
        	    {
        	         MATCHT(14, &FOLLOW_14_in_instructions250);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionsEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_instruction_in_instructions252);
        	        instruction(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionsEx;
        	        }


        	        // Tiger.g:35:21: ( ';' instruction )*

        	        for (;;)
        	        {
        	            int alt1=2;
        	            switch ( LA(1) )
        	            {
        	            case 23:
        	            	{
        	            		alt1=1;
        	            	}
        	                break;

        	            }

        	            switch (alt1)
        	            {
        	        	case 1:
        	        	    // Tiger.g:35:22: ';' instruction
        	        	    {
        	        	         MATCHT(23, &FOLLOW_23_in_instructions255);
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleinstructionsEx;
        	        	        }


        	        	        FOLLOWPUSH(FOLLOW_instruction_in_instructions257);
        	        	        instruction(ctx);

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleinstructionsEx;
        	        	        }


        	        	    }
        	        	    break;

        	        	default:
        	        	    goto loop1;	/* break out of the loop */
        	        	    break;
        	            }
        	        }
        	        loop1: ; /* Jump out to here if this rule does not match */


        	         MATCHT(15, &FOLLOW_15_in_instructions261);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionsEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleinstructionsEx; /* Prevent compiler warnings */
    ruleinstructionsEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end instructions */

/**
 * $ANTLR start params
 * Tiger.g:39:1: params : '(' ( param ( ',' param )* )? ')' ;
 */
static void
params(pTigerParser ctx)
{
    /* Initialize rule variables
     */

    {
        // Tiger.g:39:8: ( '(' ( param ( ',' param )* )? ')' )
        // Tiger.g:39:10: '(' ( param ( ',' param )* )? ')'
        {
             MATCHT(14, &FOLLOW_14_in_params273);
            if  (HASEXCEPTION())
            {
                goto ruleparamsEx;
            }


            // Tiger.g:39:14: ( param ( ',' param )* )?
            {
                int alt4=2;
                switch ( LA(1) )
                {
                    case ID:
                    	{
                    		alt4=1;
                    	}
                        break;
                }

                switch (alt4)
                {
            	case 1:
            	    // Tiger.g:39:16: param ( ',' param )*
            	    {
            	        FOLLOWPUSH(FOLLOW_param_in_params277);
            	        param(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleparamsEx;
            	        }


            	        // Tiger.g:39:22: ( ',' param )*

            	        for (;;)
            	        {
            	            int alt3=2;
            	            switch ( LA(1) )
            	            {
            	            case 18:
            	            	{
            	            		alt3=1;
            	            	}
            	                break;

            	            }

            	            switch (alt3)
            	            {
            	        	case 1:
            	        	    // Tiger.g:39:23: ',' param
            	        	    {
            	        	         MATCHT(18, &FOLLOW_18_in_params280);
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruleparamsEx;
            	        	        }


            	        	        FOLLOWPUSH(FOLLOW_param_in_params282);
            	        	        param(ctx);

            	        	        FOLLOWPOP();
            	        	        if  (HASEXCEPTION())
            	        	        {
            	        	            goto ruleparamsEx;
            	        	        }


            	        	    }
            	        	    break;

            	        	default:
            	        	    goto loop3;	/* break out of the loop */
            	        	    break;
            	            }
            	        }
            	        loop3: ; /* Jump out to here if this rule does not match */


            	    }
            	    break;

                }
            }

             MATCHT(15, &FOLLOW_15_in_params288);
            if  (HASEXCEPTION())
            {
                goto ruleparamsEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleparamsEx; /* Prevent compiler warnings */
    ruleparamsEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end params */

/**
 * $ANTLR start param
 * Tiger.g:40:1: param : ID ':' ID ;
 */
static void
param(pTigerParser ctx)
{
    /* Initialize rule variables
     */

    {
        // Tiger.g:40:8: ( ID ':' ID )
        // Tiger.g:40:10: ID ':' ID
        {
             MATCHT(ID, &FOLLOW_ID_in_param297);
            if  (HASEXCEPTION())
            {
                goto ruleparamEx;
            }


             MATCHT(21, &FOLLOW_21_in_param299);
            if  (HASEXCEPTION())
            {
                goto ruleparamEx;
            }


             MATCHT(ID, &FOLLOW_ID_in_param301);
            if  (HASEXCEPTION())
            {
                goto ruleparamEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleparamEx; /* Prevent compiler warnings */
    ruleparamEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end param */

/**
 * $ANTLR start declararion
 * Tiger.g:44:1: declararion : ( 'var' ID ( ':' ID )? ':=' value | 'function' ID params ( ':' ID )? '=' instructions );
 */
static void
declararion(pTigerParser ctx)
{
    /* Initialize rule variables
     */

    {
        {
            //  Tiger.g:45:3: ( 'var' ID ( ':' ID )? ':=' value | 'function' ID params ( ':' ID )? '=' instructions )

            ANTLR3_UINT32 alt7;

            alt7=2;

            switch ( LA(1) )
            {
            case 42:
            	{
            		alt7=1;
            	}
                break;
            case 35:
            	{
            		alt7=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 7;
                EXCEPTION->state        = 0;


                goto ruledeclararionEx;

            }

            switch (alt7)
            {
        	case 1:
        	    // Tiger.g:45:5: 'var' ID ( ':' ID )? ':=' value
        	    {
        	         MATCHT(42, &FOLLOW_42_in_declararion314);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledeclararionEx;
        	        }


        	         MATCHT(ID, &FOLLOW_ID_in_declararion316);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledeclararionEx;
        	        }


        	        // Tiger.g:45:14: ( ':' ID )?
        	        {
        	            int alt5=2;
        	            switch ( LA(1) )
        	            {
        	                case 21:
        	                	{
        	                		alt5=1;
        	                	}
        	                    break;
        	            }

        	            switch (alt5)
        	            {
        	        	case 1:
        	        	    // Tiger.g:45:15: ':' ID
        	        	    {
        	        	         MATCHT(21, &FOLLOW_21_in_declararion319);
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruledeclararionEx;
        	        	        }


        	        	         MATCHT(ID, &FOLLOW_ID_in_declararion321);
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruledeclararionEx;
        	        	        }


        	        	    }
        	        	    break;

        	            }
        	        }

        	         MATCHT(22, &FOLLOW_22_in_declararion325);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledeclararionEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_value_in_declararion327);
        	        value(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledeclararionEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // Tiger.g:46:5: 'function' ID params ( ':' ID )? '=' instructions
        	    {
        	         MATCHT(35, &FOLLOW_35_in_declararion333);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledeclararionEx;
        	        }


        	         MATCHT(ID, &FOLLOW_ID_in_declararion335);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledeclararionEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_params_in_declararion337);
        	        params(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledeclararionEx;
        	        }


        	        // Tiger.g:46:26: ( ':' ID )?
        	        {
        	            int alt6=2;
        	            switch ( LA(1) )
        	            {
        	                case 21:
        	                	{
        	                		alt6=1;
        	                	}
        	                    break;
        	            }

        	            switch (alt6)
        	            {
        	        	case 1:
        	        	    // Tiger.g:46:27: ':' ID
        	        	    {
        	        	         MATCHT(21, &FOLLOW_21_in_declararion340);
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruledeclararionEx;
        	        	        }


        	        	         MATCHT(ID, &FOLLOW_ID_in_declararion342);
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruledeclararionEx;
        	        	        }


        	        	    }
        	        	    break;

        	            }
        	        }

        	         MATCHT(27, &FOLLOW_27_in_declararion346);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledeclararionEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_instructions_in_declararion348);
        	        instructions(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruledeclararionEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruledeclararionEx; /* Prevent compiler warnings */
    ruledeclararionEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end declararion */

/**
 * $ANTLR start instruction
 * Tiger.g:52:1: instruction : ( 'let' ( declararion )+ 'in' ( instructions )* 'end' | ID ':=' value | 'if' value 'then' instructions ( options {greedy=true; } : 'else' instructions )? | 'while' value 'do' instructions | 'for' ID ':=' value 'to' value 'do' instructions | 'break' | value );
 */
static void
instruction(pTigerParser ctx)
{
    /* Initialize rule variables
     */

    {
        {
            //  Tiger.g:53:3: ( 'let' ( declararion )+ 'in' ( instructions )* 'end' | ID ':=' value | 'if' value 'then' instructions ( options {greedy=true; } : 'else' instructions )? | 'while' value 'do' instructions | 'for' ID ':=' value 'to' value 'do' instructions | 'break' | value )

            ANTLR3_UINT32 alt11;

            alt11=7;

            switch ( LA(1) )
            {
            case 38:
            	{
            		alt11=1;
            	}
                break;
            case ID:
            	{
            		switch ( LA(2) )
            		{
            		case 22:
            			{
            				alt11=2;
            			}
            		    break;
            		case EOF:
            		case ID:
            		case INTEGER:
            		case STRING:
            		case 13:
            		case 14:
            		case 15:
            		case 16:
            		case 17:
            		case 19:
            		case 20:
            		case 23:
            		case 24:
            		case 25:
            		case 26:
            		case 27:
            		case 28:
            		case 29:
            		case 30:
            		case 32:
            		case 33:
            		case 34:
            		case 35:
            		case 36:
            		case 37:
            		case 38:
            		case 39:
            		case 42:
            		case 43:
            		case 44:
            			{
            				alt11=7;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 11;
            		    EXCEPTION->state        = 2;


            		    goto ruleinstructionEx;

            		}

            	}
                break;
            case 36:
            	{
            		alt11=3;
            	}
                break;
            case 43:
            	{
            		alt11=4;
            	}
                break;
            case 34:
            	{
            		alt11=5;
            	}
                break;
            case 30:
            	{
            		alt11=6;
            	}
                break;
            case INTEGER:
            case STRING:
            case 39:
            	{
            		alt11=7;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 11;
                EXCEPTION->state        = 0;


                goto ruleinstructionEx;

            }

            switch (alt11)
            {
        	case 1:
        	    // Tiger.g:53:5: 'let' ( declararion )+ 'in' ( instructions )* 'end'
        	    {
        	         MATCHT(38, &FOLLOW_38_in_instruction364);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	        // Tiger.g:53:11: ( declararion )+
        	        {
        	            int cnt8=0;

        	            for (;;)
        	            {
        	                int alt8=2;
        	        	switch ( LA(1) )
        	        	{
        	        	case 35:
        	        	case 42:
        	        		{
        	        			alt8=1;
        	        		}
        	        	    break;

        	        	}

        	        	switch (alt8)
        	        	{
        	        	    case 1:
        	        	        // Tiger.g:53:11: declararion
        	        	        {
        	        	            FOLLOWPUSH(FOLLOW_declararion_in_instruction366);
        	        	            declararion(ctx);

        	        	            FOLLOWPOP();
        	        	            if  (HASEXCEPTION())
        	        	            {
        	        	                goto ruleinstructionEx;
        	        	            }


        	        	        }
        	        	        break;

        	        	    default:

        	        		if ( cnt8 >= 1 )
        	        		{
        	        		    goto loop8;
        	        		}
        	        		/* mismatchedSetEx()
        	        		 */
        	        		CONSTRUCTEX();
        	        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        	        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        	        		goto ruleinstructionEx;
        	        	}
        	        	cnt8++;
        	            }
        	            loop8: ;	/* Jump to here if this rule does not match */
        	        }

        	         MATCHT(37, &FOLLOW_37_in_instruction369);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	        // Tiger.g:53:29: ( instructions )*

        	        for (;;)
        	        {
        	            int alt9=2;
        	            switch ( LA(1) )
        	            {
        	            case ID:
        	            case INTEGER:
        	            case STRING:
        	            case 14:
        	            case 30:
        	            case 34:
        	            case 36:
        	            case 38:
        	            case 39:
        	            case 43:
        	            	{
        	            		alt9=1;
        	            	}
        	                break;

        	            }

        	            switch (alt9)
        	            {
        	        	case 1:
        	        	    // Tiger.g:53:29: instructions
        	        	    {
        	        	        FOLLOWPUSH(FOLLOW_instructions_in_instruction371);
        	        	        instructions(ctx);

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleinstructionEx;
        	        	        }


        	        	    }
        	        	    break;

        	        	default:
        	        	    goto loop9;	/* break out of the loop */
        	        	    break;
        	            }
        	        }
        	        loop9: ; /* Jump out to here if this rule does not match */


        	         MATCHT(33, &FOLLOW_33_in_instruction374);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // Tiger.g:55:5: ID ':=' value
        	    {
        	         MATCHT(ID, &FOLLOW_ID_in_instruction381);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	         MATCHT(22, &FOLLOW_22_in_instruction383);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_value_in_instruction385);
        	        value(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	    }
        	    break;
        	case 3:
        	    // Tiger.g:57:5: 'if' value 'then' instructions ( options {greedy=true; } : 'else' instructions )?
        	    {
        	         MATCHT(36, &FOLLOW_36_in_instruction392);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_value_in_instruction394);
        	        value(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	         MATCHT(40, &FOLLOW_40_in_instruction396);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_instructions_in_instruction398);
        	        instructions(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	        // Tiger.g:57:36: ( options {greedy=true; } : 'else' instructions )?
        	        {
        	            int alt10=2;
        	            switch ( LA(1) )
        	            {
        	                case 32:
        	                	{
        	                		alt10=1;
        	                	}
        	                    break;
        	            }

        	            switch (alt10)
        	            {
        	        	case 1:
        	        	    // Tiger.g:57:62: 'else' instructions
        	        	    {
        	        	         MATCHT(32, &FOLLOW_32_in_instruction410);
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleinstructionEx;
        	        	        }


        	        	        FOLLOWPUSH(FOLLOW_instructions_in_instruction412);
        	        	        instructions(ctx);

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleinstructionEx;
        	        	        }


        	        	    }
        	        	    break;

        	            }
        	        }

        	    }
        	    break;
        	case 4:
        	    // Tiger.g:58:5: 'while' value 'do' instructions
        	    {
        	         MATCHT(43, &FOLLOW_43_in_instruction420);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_value_in_instruction422);
        	        value(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	         MATCHT(31, &FOLLOW_31_in_instruction424);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_instructions_in_instruction426);
        	        instructions(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	    }
        	    break;
        	case 5:
        	    // Tiger.g:59:5: 'for' ID ':=' value 'to' value 'do' instructions
        	    {
        	         MATCHT(34, &FOLLOW_34_in_instruction432);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	         MATCHT(ID, &FOLLOW_ID_in_instruction434);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	         MATCHT(22, &FOLLOW_22_in_instruction436);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_value_in_instruction438);
        	        value(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	         MATCHT(41, &FOLLOW_41_in_instruction440);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_value_in_instruction442);
        	        value(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	         MATCHT(31, &FOLLOW_31_in_instruction444);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	        FOLLOWPUSH(FOLLOW_instructions_in_instruction446);
        	        instructions(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	    }
        	    break;
        	case 6:
        	    // Tiger.g:60:5: 'break'
        	    {
        	         MATCHT(30, &FOLLOW_30_in_instruction452);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	    }
        	    break;
        	case 7:
        	    // Tiger.g:62:5: value
        	    {
        	        FOLLOWPUSH(FOLLOW_value_in_instruction459);
        	        value(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleinstructionEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleinstructionEx; /* Prevent compiler warnings */
    ruleinstructionEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end instruction */

/**
 * $ANTLR start atom
 * Tiger.g:67:1: atom : ( ID | ID '(' ( ID ( ',' ID )* )? ')' ';' | STRING | INTEGER | 'nil' );
 */
static void
atom(pTigerParser ctx)
{
    /* Initialize rule variables
     */

    {
        {
            //  Tiger.g:68:3: ( ID | ID '(' ( ID ( ',' ID )* )? ')' ';' | STRING | INTEGER | 'nil' )

            ANTLR3_UINT32 alt14;

            alt14=5;

            switch ( LA(1) )
            {
            case ID:
            	{
            		switch ( LA(2) )
            		{
            		case 14:
            			{
            				switch ( LA(3) )
            				{
            				case ID:
            					{
            						switch ( LA(4) )
            						{
            						case 13:
            						case 14:
            						case 16:
            						case 17:
            						case 19:
            						case 20:
            						case 22:
            						case 23:
            						case 24:
            						case 25:
            						case 26:
            						case 27:
            						case 28:
            						case 29:
            						case 44:
            							{
            								alt14=1;
            							}
            						    break;
            						case 18:
            							{
            								alt14=2;
            							}
            						    break;
            						case 15:
            							{
            								switch ( LA(5) )
            								{
            								case 23:
            									{
            										alt14=2;
            									}
            								    break;
            								case ID:
            								case INTEGER:
            								case STRING:
            								case 14:
            								case 30:
            								case 33:
            								case 34:
            								case 36:
            								case 38:
            								case 39:
            								case 43:
            									{
            										alt14=1;
            									}
            								    break;

            								default:
            								    CONSTRUCTEX();
            								    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            								    EXCEPTION->message      = (void *)"";
            								    EXCEPTION->decisionNum  = 14;
            								    EXCEPTION->state        = 9;


            								    goto ruleatomEx;

            								}

            							}
            						    break;

            						default:
            						    CONSTRUCTEX();
            						    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            						    EXCEPTION->message      = (void *)"";
            						    EXCEPTION->decisionNum  = 14;
            						    EXCEPTION->state        = 7;


            						    goto ruleatomEx;

            						}

            					}
            				    break;
            				case 15:
            					{
            						alt14=2;
            					}
            				    break;
            				case INTEGER:
            				case STRING:
            				case 30:
            				case 34:
            				case 36:
            				case 38:
            				case 39:
            				case 43:
            					{
            						alt14=1;
            					}
            				    break;

            				default:
            				    CONSTRUCTEX();
            				    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            				    EXCEPTION->message      = (void *)"";
            				    EXCEPTION->decisionNum  = 14;
            				    EXCEPTION->state        = 5;


            				    goto ruleatomEx;

            				}

            			}
            		    break;
            		case EOF:
            		case ID:
            		case INTEGER:
            		case STRING:
            		case 13:
            		case 15:
            		case 16:
            		case 17:
            		case 19:
            		case 20:
            		case 23:
            		case 24:
            		case 25:
            		case 26:
            		case 27:
            		case 28:
            		case 29:
            		case 30:
            		case 31:
            		case 32:
            		case 33:
            		case 34:
            		case 35:
            		case 36:
            		case 37:
            		case 38:
            		case 39:
            		case 40:
            		case 41:
            		case 42:
            		case 43:
            		case 44:
            			{
            				alt14=1;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 14;
            		    EXCEPTION->state        = 1;


            		    goto ruleatomEx;

            		}

            	}
                break;
            case STRING:
            	{
            		alt14=3;
            	}
                break;
            case INTEGER:
            	{
            		alt14=4;
            	}
                break;
            case 39:
            	{
            		alt14=5;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 14;
                EXCEPTION->state        = 0;


                goto ruleatomEx;

            }

            switch (alt14)
            {
        	case 1:
        	    // Tiger.g:68:5: ID
        	    {
        	         MATCHT(ID, &FOLLOW_ID_in_atom474);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // Tiger.g:70:5: ID '(' ( ID ( ',' ID )* )? ')' ';'
        	    {
        	         MATCHT(ID, &FOLLOW_ID_in_atom481);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	         MATCHT(14, &FOLLOW_14_in_atom483);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	        // Tiger.g:70:12: ( ID ( ',' ID )* )?
        	        {
        	            int alt13=2;
        	            switch ( LA(1) )
        	            {
        	                case ID:
        	                	{
        	                		alt13=1;
        	                	}
        	                    break;
        	            }

        	            switch (alt13)
        	            {
        	        	case 1:
        	        	    // Tiger.g:70:13: ID ( ',' ID )*
        	        	    {
        	        	         MATCHT(ID, &FOLLOW_ID_in_atom486);
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleatomEx;
        	        	        }


        	        	        // Tiger.g:70:16: ( ',' ID )*

        	        	        for (;;)
        	        	        {
        	        	            int alt12=2;
        	        	            switch ( LA(1) )
        	        	            {
        	        	            case 18:
        	        	            	{
        	        	            		alt12=1;
        	        	            	}
        	        	                break;

        	        	            }

        	        	            switch (alt12)
        	        	            {
        	        	        	case 1:
        	        	        	    // Tiger.g:70:17: ',' ID
        	        	        	    {
        	        	        	         MATCHT(18, &FOLLOW_18_in_atom489);
        	        	        	        if  (HASEXCEPTION())
        	        	        	        {
        	        	        	            goto ruleatomEx;
        	        	        	        }


        	        	        	         MATCHT(ID, &FOLLOW_ID_in_atom491);
        	        	        	        if  (HASEXCEPTION())
        	        	        	        {
        	        	        	            goto ruleatomEx;
        	        	        	        }


        	        	        	    }
        	        	        	    break;

        	        	        	default:
        	        	        	    goto loop12;	/* break out of the loop */
        	        	        	    break;
        	        	            }
        	        	        }
        	        	        loop12: ; /* Jump out to here if this rule does not match */


        	        	    }
        	        	    break;

        	            }
        	        }

        	         MATCHT(15, &FOLLOW_15_in_atom497);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	         MATCHT(23, &FOLLOW_23_in_atom499);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	    }
        	    break;
        	case 3:
        	    // Tiger.g:72:5: STRING
        	    {
        	         MATCHT(STRING, &FOLLOW_STRING_in_atom506);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	    }
        	    break;
        	case 4:
        	    // Tiger.g:73:5: INTEGER
        	    {
        	         MATCHT(INTEGER, &FOLLOW_INTEGER_in_atom512);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	    }
        	    break;
        	case 5:
        	    // Tiger.g:74:5: 'nil'
        	    {
        	         MATCHT(39, &FOLLOW_39_in_atom518);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleatomEx;
        	        }


        	    }
        	    break;

            }
        }
    }

    // This is where rules clean up and exit
    //
    goto ruleatomEx; /* Prevent compiler warnings */
    ruleatomEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end atom */

/**
 * $ANTLR start value
 * Tiger.g:79:1: value : or ;
 */
static void
value(pTigerParser ctx)
{
    /* Initialize rule variables
     */

    {
        // Tiger.g:80:3: ( or )
        // Tiger.g:80:5: or
        {
            FOLLOWPUSH(FOLLOW_or_in_value533);
            or(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulevalueEx;
            }


        }

    }

    // This is where rules clean up and exit
    //
    goto rulevalueEx; /* Prevent compiler warnings */
    rulevalueEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end value */

/**
 * $ANTLR start addition
 * Tiger.g:83:1: addition : multiplication ( ( '+' | '-' ) multiplication )* ;
 */
static void
addition(pTigerParser ctx)
{
    /* Initialize rule variables
     */

    {
        // Tiger.g:84:3: ( multiplication ( ( '+' | '-' ) multiplication )* )
        // Tiger.g:84:5: multiplication ( ( '+' | '-' ) multiplication )*
        {
            FOLLOWPUSH(FOLLOW_multiplication_in_addition546);
            multiplication(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleadditionEx;
            }


            // Tiger.g:84:20: ( ( '+' | '-' ) multiplication )*

            for (;;)
            {
                int alt15=2;
                switch ( LA(1) )
                {
                case 17:
                case 19:
                	{
                		alt15=1;
                	}
                    break;

                }

                switch (alt15)
                {
            	case 1:
            	    // Tiger.g:84:21: ( '+' | '-' ) multiplication
            	    {
            	        if ( LA(1) == 17 || LA(1) == 19 )
            	        {
            	            CONSUME();
            	            PERRORRECOVERY=ANTLR3_FALSE;
            	        }
            	        else
            	        {
            	            CONSTRUCTEX();
            	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
            	            EXCEPTION->expectingSet = NULL;

            	            goto ruleadditionEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_multiplication_in_addition555);
            	        multiplication(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleadditionEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop15;	/* break out of the loop */
            	    break;
                }
            }
            loop15: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleadditionEx; /* Prevent compiler warnings */
    ruleadditionEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end addition */

/**
 * $ANTLR start multiplication
 * Tiger.g:86:1: multiplication : atom ( ( '*' | '/' ) atom )* ;
 */
static void
multiplication(pTigerParser ctx)
{
    /* Initialize rule variables
     */

    {
        // Tiger.g:87:3: ( atom ( ( '*' | '/' ) atom )* )
        // Tiger.g:87:5: atom ( ( '*' | '/' ) atom )*
        {
            FOLLOWPUSH(FOLLOW_atom_in_multiplication569);
            atom(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulemultiplicationEx;
            }


            // Tiger.g:87:10: ( ( '*' | '/' ) atom )*

            for (;;)
            {
                int alt16=2;
                switch ( LA(1) )
                {
                case 16:
                case 20:
                	{
                		alt16=1;
                	}
                    break;

                }

                switch (alt16)
                {
            	case 1:
            	    // Tiger.g:87:11: ( '*' | '/' ) atom
            	    {
            	        if ( LA(1) == 16 || LA(1) == 20 )
            	        {
            	            CONSUME();
            	            PERRORRECOVERY=ANTLR3_FALSE;
            	        }
            	        else
            	        {
            	            CONSTRUCTEX();
            	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
            	            EXCEPTION->expectingSet = NULL;

            	            goto rulemultiplicationEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_atom_in_multiplication578);
            	        atom(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulemultiplicationEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop16;	/* break out of the loop */
            	    break;
                }
            }
            loop16: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto rulemultiplicationEx; /* Prevent compiler warnings */
    rulemultiplicationEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end multiplication */

/**
 * $ANTLR start or
 * Tiger.g:90:1: or : and ( '|' and )* ;
 */
static void
or(pTigerParser ctx)
{
    /* Initialize rule variables
     */

    {
        // Tiger.g:91:3: ( and ( '|' and )* )
        // Tiger.g:91:5: and ( '|' and )*
        {
            FOLLOWPUSH(FOLLOW_and_in_or593);
            and(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleorEx;
            }


            // Tiger.g:91:9: ( '|' and )*

            for (;;)
            {
                int alt17=2;
                switch ( LA(1) )
                {
                case 44:
                	{
                		alt17=1;
                	}
                    break;

                }

                switch (alt17)
                {
            	case 1:
            	    // Tiger.g:91:10: '|' and
            	    {
            	         MATCHT(44, &FOLLOW_44_in_or596);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleorEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_and_in_or598);
            	        and(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleorEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop17;	/* break out of the loop */
            	    break;
                }
            }
            loop17: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleorEx; /* Prevent compiler warnings */
    ruleorEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end or */

/**
 * $ANTLR start and
 * Tiger.g:93:1: and : comparison ( '&' comparison )* ;
 */
static void
and(pTigerParser ctx)
{
    /* Initialize rule variables
     */

    {
        // Tiger.g:94:3: ( comparison ( '&' comparison )* )
        // Tiger.g:94:5: comparison ( '&' comparison )*
        {
            FOLLOWPUSH(FOLLOW_comparison_in_and612);
            comparison(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto ruleandEx;
            }


            // Tiger.g:94:16: ( '&' comparison )*

            for (;;)
            {
                int alt18=2;
                switch ( LA(1) )
                {
                case 13:
                	{
                		alt18=1;
                	}
                    break;

                }

                switch (alt18)
                {
            	case 1:
            	    // Tiger.g:94:17: '&' comparison
            	    {
            	         MATCHT(13, &FOLLOW_13_in_and615);
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleandEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_comparison_in_and617);
            	        comparison(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleandEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop18;	/* break out of the loop */
            	    break;
                }
            }
            loop18: ; /* Jump out to here if this rule does not match */


        }

    }

    // This is where rules clean up and exit
    //
    goto ruleandEx; /* Prevent compiler warnings */
    ruleandEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end and */

/**
 * $ANTLR start comparison
 * Tiger.g:96:1: comparison : addition ( ( '=' | '<>' | '<' | '>' | '<=' | '>=' ) addition )? ;
 */
static void
comparison(pTigerParser ctx)
{
    /* Initialize rule variables
     */

    {
        // Tiger.g:97:3: ( addition ( ( '=' | '<>' | '<' | '>' | '<=' | '>=' ) addition )? )
        // Tiger.g:97:5: addition ( ( '=' | '<>' | '<' | '>' | '<=' | '>=' ) addition )?
        {
            FOLLOWPUSH(FOLLOW_addition_in_comparison631);
            addition(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulecomparisonEx;
            }


            // Tiger.g:97:14: ( ( '=' | '<>' | '<' | '>' | '<=' | '>=' ) addition )?
            {
                int alt19=2;
                switch ( LA(1) )
                {
                    case 24:
                    case 25:
                    case 26:
                    case 27:
                    case 28:
                    case 29:
                    	{
                    		alt19=1;
                    	}
                        break;
                }

                switch (alt19)
                {
            	case 1:
            	    // Tiger.g:97:15: ( '=' | '<>' | '<' | '>' | '<=' | '>=' ) addition
            	    {
            	        if ( ((LA(1) >= 24) && (LA(1) <= 29)) )
            	        {
            	            CONSUME();
            	            PERRORRECOVERY=ANTLR3_FALSE;
            	        }
            	        else
            	        {
            	            CONSTRUCTEX();
            	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
            	            EXCEPTION->expectingSet = NULL;

            	            goto rulecomparisonEx;
            	        }


            	        FOLLOWPUSH(FOLLOW_addition_in_comparison648);
            	        addition(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulecomparisonEx;
            	        }


            	    }
            	    break;

                }
            }

        }

    }

    // This is where rules clean up and exit
    //
    goto rulecomparisonEx; /* Prevent compiler warnings */
    rulecomparisonEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }
    return ;
}
/* $ANTLR end comparison */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */






/* End of code
 * =============================================================================
 */
